spring.application.name=GESTION_PROFESION
spring.datasource.url=jdbc:mysql://localhost:3306/profesion_springboot
spring.datasource.username=root
spring.datasource.password=leavemealone09
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.mvc.throw-exception-if-no-handler-found=true